### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by muralikodali** [pcasaretto/atom-tabularize#21] opened 2015-06-05 16:59 UTC
"GOOG",517.54,"10/7/2009","4:00pm",+18.80,498.97,518.99,497.81,4877683
"YHOO",17.49,"10/7/2009","4:00pm",+0.19,17.24,17.49,17.15,12463817
"RHT",27.91,"10/7/2009","4:05pm",-0.05,27.96,27.96,27.47,1319059
"ETFC",1.69,"10/7/2009","4:00pm",-0.01,1.71,1.74,1.66,171823488
"IBM",122.78,"10/7/2009","4:00pm",+1.43,121.12,122.85,120.94,5967677
"JAVA",8.95,"10/7/2009","4:00pm",+0.05,8.88,9.03,8.81,24210714
"VMW",41.84,"10/7/2009","4:01pm",+0.73,40.86,41.96,40.86,1250141
"CTXS",39.57,"10/7/2009","4:00pm",-0.51,39.86,39.89,39.11,3638443
"FIRE",21.85,"10/7/2009","4:00pm",+0.08,21.73,21.95,21.59,112475

**Comment by pcasaretto** [comment] 2015-06-05 17:02
Duplicate of #15 .
Thanks for reporting.

**Closed by pcasaretto** 2015-06-05 17:02 UTC
