### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kerbyfc** [pcasaretto/atom-tabularize#17] opened 2014-12-29 10:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tabularize](https://github.com/pcasaretto/atom-tabularize) package, v0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: Cannot read property 'length' of null
  at Function.module.exports.Tabularize.leftAlign (/Users/kerbyfc/.atom/packages/tabularize/lib/tabularize.coffee:56:35)
  at Function.module.exports.Tabularize.paddingColumn (/Users/kerbyfc/.atom/packages/tabularize/lib/tabularize.coffee:78:19)
  at /Users/kerbyfc/.atom/packages/tabularize/lib/tabularize.coffee:35:38
  at /Users/kerbyfc/.atom/packages/tabularize/lib/tabularize.coffee:41:11
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:777:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:19)
  at Function.module.exports.Tabularize.tabularize (/Users/kerbyfc/.atom/packages/tabularize/lib/tabularize.coffee:17:14)
  at TabularizeView.module.exports.TabularizeView.confirm (/Users/kerbyfc/.atom/packages/tabularize/lib/tabularize-view.coffee:53:16)
  at HTMLDivElement.<anonymous> (/Users/kerbyfc/.atom/packages/tabularize/lib/tabularize-view.coffee:25:29)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:09.5 vim-mode:activate-command-mode (input.hidden-input)
  4x -0:09.5 vim-mode:move-up (input.hidden-input)
     -0:08.8 vim-mode:activate-linewise-visual-mode (input.hidden-input)
     -0:08.4 vim-mode:activate-command-mode (input.hidden-input)
     -0:08.2 vim-mode:move-down (input.hidden-input)
     -0:08.0 vim-mode:activate-linewise-visual-mode (input.hidden-input)
     -0:07.9 vim-mode:move-down (input.hidden-input)
     -0:07.4 vim-mode:activate-command-mode (input.hidden-input)
  3x -0:07.3 vim-mode:move-up (input.hidden-input)
     -0:06.7 vim-mode:activate-linewise-visual-mode (input.hidden-input)
  9x -0:06.4 vim-mode:move-down (input.hidden-input)
     -0:04.2 command-palette:toggle (input.hidden-input)
  2x -0:02.1 core:backspace (input.hidden-input)
     -0:01.2 core:confirm (input.hidden-input)
     -0:01.2 tabularize:toggle (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "tomorrow-night-bright-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "relative-numbers"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.3
autocomplete-paths, v0.9.1
autocomplete-plus, v1.0.0
jumpy, v1.9.4
neon-cursor, v0.2.0
seti-ui, v0.5.1
tabularize, v0.2.2
tomorrow-night-bright-syntax, v0.1.0
vim-mode, v0.22.0
vim-surround, v0.2.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by guih** [comment] 2015-01-20 14:57
This happened here too

**Comment by pcasaretto** [comment] 2015-01-20 16:49
Thanks for report guys. Closing it because it is a duplicate of #15 .

**Closed by pcasaretto** 2015-01-20 16:49 UTC
